server:
  port: 8798

ms-config:
  username: root
  password: 123456
  driver-class: com.mysql.cj.jdbc.Driver
  hibernate-dialect: org.hibernate.dialect.MySQLDialect
  databases:
    products:
      url: jdbc:mysql://localhost:3306/products
    clients:
      url: jdbc:mysql://localhost:3306/clients